# VARIABLES
#

TARGET=deckard

COCCI="../vanillacocci"

SYSLIBS="str.cma unix.cma"

#LIBS="$(COCCI)/commons/

MAKESUBDIRS=$(COCCI)/commons $(COCCI)/globals $(COCCI)/menhirlib $(COCCI)/parsing_cocci $(COCCI)/parsing_c
INCLUDEDIRS=$(COCCI)/commons $(COCCI)/commons/ocamlextra $(COCCI)/globals $(COCCI)/commons/ocollection $(COCCI)/globals $(COCCI)/parsing_c
